---
- name: Terminate every running instance in a region. Use with EXTREME caution.
  amazon.aws.ec2_instance:
    state: absent
    region: us-east-1
    filters:
      instance-state-name: running
    tags: 
      Name: ansible-instance
      Environment: Testing tasks file for ec2